%% Simulate multitrial VAR data by simulating each trials
% Observations:
% Multitrial model orders tend to be higher than per trials model orders
% when per trial data is generated by VAR of model order 5 with different
% coefficient. But with same coefficients, we have same global model order
% as per trial model order. Interestingly if per-trials residuals and
% VAR coefficients are different, global VAR model is still stable but with
% much higher model orderl. 
%% Parameters
rng(1);
ntrials = 56;
tsdim = 4;
morder = 5;
rho = 0.90;
nobs = 350;
regmode = 'OLS';
momax = 10;
alpha = 0.05;
pacf = true;
plotm = 1;
verb = 0;

%%

Y = var_simulation(tsdim, 'morder', morder, 'specrad', rho, 'nobs', nobs, 'ntrials', 1);

%%
connectivity_matrix = randi([0 1], tsdim);
for i = 1:tsdim
    connectivity_matrix(i,i) = 0;
end

var_coef = var_rand(connectivity_matrix,morder,rho,[]);
corr_res = corr_rand(tsdim,[]); 
%% Simulation
X = zeros(tsdim, nobs, ntrials);
for i=1:ntrials
    X(:,:,i) = var_to_tsdata(var_coef,corr_res,nobs,1);
end
disp(size(X))
%% Estimate global moder
clear moaic mobic mohqc molrt

[moaic,mobic,mohqc,molrt] = tsdata_to_varmo(X, momax,regmode,alpha,pacf,plotm,verb);
    
%% Esitmate global VAR

VAR = ts_to_var_parameters(X, 'morder', morder, 'regmode', regmode);

%% Estimate VAR model order on each trial
moaic = zeros(ntrials, 1);
mobic = zeros(ntrials, 1);
mohqc = zeros(ntrials, 1);
molrt = zeros(ntrials, 1);

for itrial=1:ntrials
    [moaic(itrial),mobic(itrial),mohqc(itrial),molrt(itrial)] =  ... 
        tsdata_to_varmo(X(:,:,itrial), momax,regmode,alpha,pacf,plotm,verb);
end

    
%% Estimate per trials VAR parameters

morder = 4;
for i=1:ntrials
    VAR(i) = ts_to_var_parameters(X(:,:,i), 'morder', morder, 'regmode', regmode);
end
